title: Researcher
url: "https://neclow.github.io"
baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/Neclow"
footer_text: "Link to GitHub account"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Resume"
   link: "__cv.pdf"
 - name: "Contact"
   link: "contact"
