author: Neil Scheidwasser
title: Neil Scheidwasser
url: "https://neclow.github.io"
baseurl: "/about"
description: "About"

markdown: kramdown
ins_logo: "./favicon_ku.ico"

tracking_id: #

footer: yes
footer_url: "https://github.com/Neclow"
footer_text: "GitHub"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Resume"
   link: "__cv.pdf"
 - name: "Contact"
   link: "contact"
