author: Neil Scheidwasser
title: Neil Scheidwasser
url: "https://neclow.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/Neclow"
footer_text: "GitHub"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "cv.pdf"

remote_theme: ankitsultana/researcher@gem